on:
  push:
    branches:
      - master
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        BUILD_DIR: website 
        # Provide personal access token
        TOKEN: ${{ secrets.PERSONAL_SITE }}
