on:
  push:
    branches:
      - master
name: Build and deploy GH Pages
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        BUILD_DIR: website 
        # Provide personal access token
        GITHUB_TOKEN: ${{ secrets.PERSONAL_SITE }}
